service: example-app
frameworkVersion: '3'

provider:
  name: aws
  stage: prod
  runtime: nodejs18.x
  region: ap-northeast-1
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
functions:
  hello:
    image: <your image uri>
    events:
    - httpApi:
        path: /hello
        method: GET
