version: 0.2
phases:
  install:
    commands:
      - npm install -g serverless 
      - npm install serverless-domain-manager
  build:
    commands:
      - serverless create_domain
      - serverless deploy 
